<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=utf-8" http-equiv="content-type">
    <title>Provas Antigas</title>
    <style type="text/css">
body {
background-color: #CCCCCC;
margin-left: 100px;
margin-top: 0px;
margin-right: 100px;
margin-bottom: 0px;
}
body,td,th {
font-family: Times New Roman, Times, serif;
font-size: 16px;
}
a {
font-weight: bold;
}
.style2 {
font-size: 50px;
color: #000010;
}
.subtitulo {
font-family:Arial
font-weight: bold;
font-size: 40px
}
.style6 {
color: #000000;
font-weight: bold;
}
.style7 {font-size: 13px; font-weight: bold; color: #000000; }
.style9 {font-size: 12px; font-weight: bold; color: #000000; }
.style10 {color: #000080}
.style11 {color: #FFFFFF}
.style13 {
color: #FFFFFF;
font-size: 12px;
font-weight: bold;
}
  </style>
  </head>


<body style="background-color: rgb(255, 255, 255); color: rgb(0, 0, 0);" alink="#ee0000" link="#0000ee" vlink="#551a8b">
  <hr>
  <table border="0" width="100%">
    <tbody>
      <tr>
        <div style="text-align: center;" class="style2">MAT01168 - Matemática Aplicada II - Avaliações antigas<br></div>
      </tr>
    </tbody>
   </table>
   <hr>

    <!-- Vetorial -->
    <br> <br>
    <div style="text-align: left;" class="subtitulo">Provas Antigas - Análise Vetorial<br></div>
    
    <table>
       <tbody>
            <!--<tr>
            <td><a href="Vetorial/prova1A20222.pdf">Turma A 2022/2 - prof. João Batista Carvalho</a></td> 
            <td></td>
            <td><a href="Vetorial/prova1A20222gab.pdf"”>Gabarito</a></td>
            </tr>-->
            ___PROVAS___VETORIAL___
            
       </tbody>
    </table>
      

    <!-- Laplace -->
    <hr><br><br>
    <div style="text-align: left;" class="subtitulo">Provas Antigas - Transformada de Laplace<br></div>

    <table>
      <tbody>
        
        ___PROVAS___LAPLACE___

      <tbody>
    </table>


    <!-- Fourier -->
    <hr><br><br>
    <div style="text-align: left;" class="subtitulo">Provas Antigas - Séries e Transformadas de Fourier<br></div>

    <table>
      <tbody>
        
        ___PROVAS___FOURIER___
       </tbody>
      </table>
    
  </body>
</html>